build:
    image: jrbeverly/pdf2htmlex
    stage: build
    script:
        - "apk --no-cache add curl zip"
        - "if [ -n ${BUILD_ID} ]; then curl -o artifacts.zip --header \"PRIVATE-TOKEN: ${ARTIFACT_TOKEN}\" \"https://gitlab.com/api/v3/projects/${PROJECT_ID}/builds/${BUILD_ID}/artifacts\"; fi "
        - "unzip artifacts.zip"
        - "mv src/manual.pdf src/index.pdf"
        - "pdf2htmlEX --zoom 1.5 --embed cfijo --dest-dir public src/index.pdf"
    only:
        - triggers
    artifacts:
        paths:
            - public

pages:
    image: alpine:latest
    stage: deploy
    script:
     - "echo 'Nothing to do'"
    only:
        - triggers
    artifacts:
        paths:
            - public
