variables:
  GITLAB_URL: "https://gitlab.com"
  NAMESPACE: "jrbeverly-friending"
  PROJECT: "friending-manual"

build:
    image: jrbeverly/pdf2htmlex:privileged
    stage: build
    script:
        - sh build/build.sh
    only:
        - triggers
        - master
    artifacts:
        paths:
            - public
        expire_in: 2 hours

pages:
    image: alpine:latest
    stage: deploy
    script:
     - "echo 'Publishing artifacts'"
    only:
        - triggers
        - master
    artifacts:
        paths:
            - public
        expire_in: 2 hours
