build:
    image: jrbeverly/pdf2htmlex
    stage: build
    script:
        - sh build/build.sh
    only:
        - triggers
    artifacts:
        paths:
            - public

pages:
    image: alpine:latest
    stage: deploy
    script:
     - "echo 'Nothing to do'"
    only:
        - triggers
    artifacts:
        paths:
            - public
