build:
    image: jrbeverly/pdf2htmlex:privileged
    stage: build
    script:
        - sh build/build.sh
    only:
        - triggers
        - master
    artifacts:
        paths:
            - public
        expire_in: 2 hours

pages:
    image: alpine:latest
    stage: deploy
    script:
     - "echo 'Nothing to do'"
    only:
        - triggers
    artifacts:
        paths:
            - public
        expire_in: 2 hours
